const { Ingredient } = require('./models')

const ingredients = [
	{
		"id": 1,
		"name": "egg white",
		"remarks": "Mast cell activating especially raw, but even cooked",
		"histamine": false,
		"other_amines": false,
		"liberator": true,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "eggs"
	},
	{
		"id": 2,
		"name": "egg yolk",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "eggs"
	},
	{
		"id": 3,
		"name": "egg, chicken egg, whole egg",
		"remarks": "Yolk is compatible. Egg white is mast cell activating especially raw, but even\ncooked",
		"histamine": false,
		"other_amines": false,
		"liberator": true,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "eggs"
	},
	{
		"id": 4,
		"name": "quail egg",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "eggs"
	},
	{
		"id": 12,
		"name": "butter",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "dairy"
	},
	{
		"id": 13,
		"name": "cheddar cheese",
		"remarks": null,
		"histamine": true,
		"other_amines": true,
		"liberator": false,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "dairy"
	},
	{
		"id": 14,
		"name": "hard cheese, matured cheese",
		"remarks": null,
		"histamine": true,
		"other_amines": true,
		"liberator": false,
		"blocker": false,
		"compatibility": 3,
		"your_compatibility": null,
		"category": "dairy"
	},
	{
		"id": 15,
		"name": "milk, lactose-free",
		"remarks": "Sometimes well tolerated, sometimes slightly worse tolerated than regular milk",
		"histamine": true,
		"other_amines": false,
		"liberator": null,
		"blocker": false,
		"compatibility": 1,
		"your_compatibility": null,
		"category": "dairy"
	},
	{
		"id": 16,
		"name": "milk, pasteurized",
		"remarks": "Milk may be incompatible, as long as the bowel is still irritated",
		"histamine": false,
		"other_amines": false,
		"liberator": null,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "dairy"
	},
	{
		"id": 17,
		"name": "milk, UHT",
		"remarks": "UHT = ultra-high temperature processing, ultra-heat treatment",
		"histamine": false,
		"other_amines": false,
		"liberator": null,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "dairy"
	},
	{
		"id": 18,
		"name": "sour cream",
		"remarks": "Lactic acid fermentation! Slightly histamine containing",
		"histamine": true,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 1,
		"your_compatibility": null,
		"category": "dairy"
	},
	{
		"id": 19,
		"name": "cream cheese",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "dairy"
	},
	{
		"id": 20,
		"name": "yoghurt",
		"remarks": "Varies by product",
		"histamine": true,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 1,
		"your_compatibility": null,
		"category": "dairy"
	},
	{
		"id": 21,
		"name": "beef, fresh",
		"remarks": null,
		"histamine": true,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "meat"
	},
	{
		"id": 22,
		"name": "chicken",
		"remarks": null,
		"histamine": true,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "meat"
	},
	{
		"id": 23,
		"name": "duck",
		"remarks": null,
		"histamine": true,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "meat"
	},
	{
		"id": 24,
		"name": "minced meat, fresh",
		"remarks": "Varies by product",
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "meat"
	},
	{
		"id": 25,
		"name": "minced meat, pre-packed",
		"remarks": "Varies by product",
		"histamine": true,
		"other_amines": true,
		"liberator": false,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "meat"
	},
	{
		"id": 26,
		"name": "pork, fresh",
		"remarks": null,
		"histamine": true,
		"other_amines": false,
		"liberator": true,
		"blocker": false,
		"compatibility": 1,
		"your_compatibility": null,
		"category": "meat"
	},
	{
		"id": 27,
		"name": "smoked fish",
		"remarks": null,
		"histamine": true,
		"other_amines": true,
		"liberator": true,
		"blocker": false,
		"compatibility": 3,
		"your_compatibility": null,
		"category": "meat"
	},
	{
		"id": 28,
		"name": "smoked meat",
		"remarks": null,
		"histamine": true,
		"other_amines": true,
		"liberator": true,
		"blocker": false,
		"compatibility": 3,
		"your_compatibility": null,
		"category": "meat"
	},
	{
		"id": 29,
		"name": "innards",
		"remarks": null,
		"histamine": true,
		"other_amines": false,
		"liberator": true,
		"blocker": false,
		"compatibility": 3,
		"your_compatibility": null,
		"category": "meat"
	},
	{
		"id": 30,
		"name": "ham",
		"remarks": null,
		"histamine": true,
		"other_amines": true,
		"liberator": null,
		"blocker": false,
		"compatibility": 3,
		"your_compatibility": null,
		"category": "meat"
	},
	{
		"id": 31,
		"name": "sausage",
		"remarks": "A few acceptable exceptions are possible",
		"histamine": true,
		"other_amines": null,
		"liberator": null,
		"blocker": false,
		"compatibility": 3,
		"your_compatibility": null,
		"category": "meat"
	},
	{
		"id": 32,
		"name": "turkey",
		"remarks": null,
		"histamine": true,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "meat"
	},
	{
		"id": 33,
		"name": "veal, fresh",
		"remarks": null,
		"histamine": true,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "meat"
	},
	{
		"id": 34,
		"name": "venison",
		"remarks": "Mostly matured meat, but fresh wild boar is well tolerated",
		"histamine": true,
		"other_amines": null,
		"liberator": false,
		"blocker": false,
		"compatibility": 1,
		"your_compatibility": null,
		"category": "meat"
	},
	{
		"id": 35,
		"name": "wild meat",
		"remarks": "Mostly matured meat, but fresh wild boar is well tolerated",
		"histamine": true,
		"other_amines": null,
		"liberator": false,
		"blocker": false,
		"compatibility": 1,
		"your_compatibility": null,
		"category": "meat"
	},
	{
		"id": 36,
		"name": "anchovies",
		"remarks": null,
		"histamine": true,
		"other_amines": true,
		"liberator": false,
		"blocker": false,
		"compatibility": 3,
		"your_compatibility": null,
		"category": "fish"
	},
	{
		"id": 37,
		"name": "fish, fresh or frozen",
		"remarks": "Extremely depending on freshness and species",
		"histamine": true,
		"other_amines": true,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "fish"
	},
	{
		"id": 38,
		"name": "fish, pre-packed or over ice",
		"remarks": "Extremely depending on freshness and species",
		"histamine": true,
		"other_amines": true,
		"liberator": false,
		"blocker": false,
		"compatibility": 3,
		"your_compatibility": null,
		"category": "fish"
	},
	{
		"id": 39,
		"name": "tuna",
		"remarks": null,
		"histamine": true,
		"other_amines": true,
		"liberator": false,
		"blocker": false,
		"compatibility": 3,
		"your_compatibility": null,
		"category": "fish"
	},
	{
		"id": 40,
		"name": "shellfish",
		"remarks": "Mussels, oysters, clams, scallops, etc.",
		"histamine": true,
		"other_amines": false,
		"liberator": true,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "seafood"
	},
	{
		"id": 41,
		"name": "crab",
		"remarks": null,
		"histamine": true,
		"other_amines": false,
		"liberator": true,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "seafood"
	},
	{
		"id": 42,
		"name": "crayfish",
		"remarks": null,
		"histamine": true,
		"other_amines": false,
		"liberator": true,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "seafood"
	},
	{
		"id": 43,
		"name": "lobster",
		"remarks": null,
		"histamine": true,
		"other_amines": false,
		"liberator": true,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "seafood"
	},
	{
		"id": 44,
		"name": "oyster",
		"remarks": null,
		"histamine": true,
		"other_amines": false,
		"liberator": true,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "seafood"
	},
	{
		"id": 45,
		"name": "prawn",
		"remarks": null,
		"histamine": true,
		"other_amines": false,
		"liberator": true,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "seafood"
	},
	{
		"id": 46,
		"name": "shrimp",
		"remarks": null,
		"histamine": true,
		"other_amines": false,
		"liberator": true,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "seafood"
	},
	{
		"id": 47,
		"name": "barley",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 1,
		"your_compatibility": null,
		"category": "starch"
	},
	{
		"id": 48,
		"name": "bread",
		"remarks": null,
		"histamine": null,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 1,
		"your_compatibility": null,
		"category": "starch"
	},
	{
		"id": 49,
		"name": "buckwheat",
		"remarks": null,
		"histamine": false,
		"other_amines": null,
		"liberator": null,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "starch"
	},
	{
		"id": 50,
		"name": "chestnut",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "starch"
	},
	{
		"id": 51,
		"name": "cornflakes",
		"remarks": "Be careful with malt, folic acid",
		"histamine": false,
		"other_amines": false,
		"liberator": true,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "starch"
	},
	{
		"id": 52,
		"name": "oats",
		"remarks": "Some varieties may sometimes be intolerated (flatulence)",
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "starch"
	},
	{
		"id": 53,
		"name": "pearl sago",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "starch"
	},
	{
		"id": 54,
		"name": "potato",
		"remarks": "Possibly incompatible for those with salicylate intolerance",
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "starch"
	},
	{
		"id": 55,
		"name": "quinoa",
		"remarks": "Possibly not always well tolerated",
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "starch"
	},
	{
		"id": 56,
		"name": "rice",
		"remarks": "After cooking, store in the fridge up to 12-24 hours max",
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "starch"
	},
	{
		"id": 57,
		"name": "rice crackers, rice cakes",
		"remarks": "Slightly worse tolerated than freshly cooked rice",
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "starch"
	},
	{
		"id": 58,
		"name": "rice crispies",
		"remarks": "Be careful with malt, folic acid",
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "starch"
	},
	{
		"id": 59,
		"name": "rice noodles",
		"remarks": "Slightly worse tolerated than freshly cooked rice",
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "starch"
	},
	{
		"id": 60,
		"name": "rye",
		"remarks": "Barely tolerated",
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 1,
		"your_compatibility": null,
		"category": "starch"
	},
	{
		"id": 61,
		"name": "sago",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "starch"
	},
	{
		"id": 62,
		"name": "spelt",
		"remarks": "Prefer old varieties. Modern ATI-varieties modified by cultivation are often not well tolerated.",
		"histamine": false,
		"other_amines": false,
		"liberator": null,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "starch"
	},
	{
		"id": 63,
		"name": "sunflower seed",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": true,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "starch"
	},
	{
		"id": 64,
		"name": "sweet corn, fresh",
		"remarks": "Hard to digest",
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "starch"
	},
	{
		"id": 65,
		"name": "sweet corn, flour",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "starch"
	},
	{
		"id": 66,
		"name": "sweet corn, canned",
		"remarks": "Hard to digest. Possibly incompatible after long-term storage or in large quantities",
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "starch"
	},
	{
		"id": 67,
		"name": "wheat",
		"remarks": "Mostly digestive problems like flatulence",
		"histamine": null,
		"other_amines": false,
		"liberator": null,
		"blocker": false,
		"compatibility": 1,
		"your_compatibility": null,
		"category": "starch"
	},
	{
		"id": 68,
		"name": "sweet potato",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "starch"
	},
	{
		"id": 69,
		"name": "wild rice",
		"remarks": "Wild rice is not botanically related to rice.",
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "starch"
	},
	{
		"id": 70,
		"name": "yam",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "starch"
	},
	{
		"id": 71,
		"name": "almond",
		"remarks": "Small amounts are well tolerated. May cause e.g. sleep problems",
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 1,
		"your_compatibility": null,
		"category": "nuts"
	},
	{
		"id": 72,
		"name": "cashew nut",
		"remarks": null,
		"histamine": false,
		"other_amines": true,
		"liberator": true,
		"blocker": false,
		"compatibility": 1,
		"your_compatibility": null,
		"category": "nuts"
	},
	{
		"id": 73,
		"name": "hazelnut",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": true,
		"blocker": false,
		"compatibility": 1,
		"your_compatibility": null,
		"category": "nuts"
	},
	{
		"id": 74,
		"name": "macadamia",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "nuts"
	},
	{
		"id": 75,
		"name": "peanut",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "nuts"
	},
	{
		"id": 76,
		"name": "pine nut",
		"remarks": "Several species. Maybe not all of them with the same compatibility",
		"histamine": false,
		"other_amines": false,
		"liberator": null,
		"blocker": false,
		"compatibility": 1,
		"your_compatibility": null,
		"category": "nuts"
	},
	{
		"id": 77,
		"name": "pistachio",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "nuts"
	},
	{
		"id": 78,
		"name": "walnut",
		"remarks": null,
		"histamine": false,
		"other_amines": true,
		"liberator": true,
		"blocker": false,
		"compatibility": 3,
		"your_compatibility": null,
		"category": "nuts"
	},
	{
		"id": 79,
		"name": "black seed oil",
		"remarks": "Antiallergic",
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "fats and oils"
	},
	{
		"id": 80,
		"name": "canola oil",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "fats and oils"
	},
	{
		"id": 81,
		"name": "coconut oil",
		"remarks": "Highly recommended",
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "fats and oils"
	},
	{
		"id": 82,
		"name": "margarine",
		"remarks": "Check for incompatible additives",
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "fats and oils"
	},
	{
		"id": 83,
		"name": "olive oil",
		"remarks": "Incompatible for those with salicylate intolerance",
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "fats and oils"
	},
	{
		"id": 84,
		"name": "palm oil",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "fats and oils"
	},
	{
		"id": 85,
		"name": "sunflower oil",
		"remarks": "A single dose is no problem, but is inflammatory in the long term",
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 1,
		"your_compatibility": null,
		"category": "fats and oils"
	},
	{
		"id": 86,
		"name": "walnut oil",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": null,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "fats and oils"
	},
	{
		"id": 87,
		"name": "artichoke",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "vegetables"
	},
	{
		"id": 88,
		"name": "asparagus",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "vegetables"
	},
	{
		"id": 89,
		"name": "avocado",
		"remarks": null,
		"histamine": true,
		"other_amines": false,
		"liberator": true,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "vegetables"
	},
	{
		"id": 90,
		"name": "beans",
		"remarks": "Applies to virtually all types / varieties. Some tolerated exceptions are possible in some cases",
		"histamine": false,
		"other_amines": false,
		"liberator": true,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "vegetables"
	},
	{
		"id": 91,
		"name": "beetroot",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "vegetables"
	},
	{
		"id": 92,
		"name": "bell pepper (hot)",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "vegetables"
	},
	{
		"id": 93,
		"name": "bell pepper (sweet)",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "vegetables"
	},
	{
		"id": 94,
		"name": "xiao bai cai",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "vegetables"
	},
	{
		"id": 95,
		"name": "brinjal",
		"remarks": null,
		"histamine": true,
		"other_amines": null,
		"liberator": null,
		"blocker": null,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "vegetables"
	},
	{
		"id": 96,
		"name": "broccoli",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "vegetables"
	},
	{
		"id": 97,
		"name": "brussels sprouts",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": true,
		"blocker": false,
		"compatibility": 1,
		"your_compatibility": null,
		"category": "vegetables"
	},
	{
		"id": 98,
		"name": "cabbage",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "vegetables"
	},
	{
		"id": 99,
		"name": "carrot",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "vegetables"
	},
	{
		"id": 100,
		"name": "cauliflower",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "vegetables"
	},
	{
		"id": 101,
		"name": "celery",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "vegetables"
	},
	{
		"id": 102,
		"name": "chickpea",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "vegetables"
	},
	{
		"id": 103,
		"name": "chilli",
		"remarks": "Hotness causes irritation",
		"histamine": false,
		"other_amines": false,
		"liberator": null,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "vegetables"
	},
	{
		"id": 104,
		"name": "cucumber",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "vegetables"
	},
	{
		"id": 105,
		"name": "garlic",
		"remarks": "In small amounts, usually well tolerated after cooking",
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 1,
		"your_compatibility": null,
		"category": "vegetables"
	},
	{
		"id": 106,
		"name": "gourd",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "vegetables"
	},
	{
		"id": 107,
		"name": "green bean",
		"remarks": "Can be well tolerated in some cases",
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 1,
		"your_compatibility": null,
		"category": "vegetables"
	},
	{
		"id": 108,
		"name": "green peas",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 1,
		"your_compatibility": null,
		"category": "vegetables"
	},
	{
		"id": 109,
		"name": "horseradish",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": true,
		"blocker": false,
		"compatibility": 1,
		"your_compatibility": null,
		"category": "vegetables"
	},
	{
		"id": 110,
		"name": "leek",
		"remarks": "In small amounts, usually well tolerated",
		"histamine": false,
		"other_amines": false,
		"liberator": true,
		"blocker": false,
		"compatibility": 1,
		"your_compatibility": null,
		"category": "vegetables"
	},
	{
		"id": 111,
		"name": "lentils",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "vegetables"
	},
	{
		"id": 112,
		"name": "lettuce",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "vegetables"
	},
	{
		"id": 113,
		"name": "olives",
		"remarks": "Usually fermented, sometimes with intolerated ingredients",
		"histamine": null,
		"other_amines": null,
		"liberator": false,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "vegetables"
	},
	{
		"id": 114,
		"name": "onion",
		"remarks": "Incompatible in large quantities",
		"histamine": false,
		"other_amines": false,
		"liberator": true,
		"blocker": false,
		"compatibility": 1,
		"your_compatibility": null,
		"category": "vegetables"
	},
	{
		"id": 115,
		"name": "pickled vegetable",
		"remarks": null,
		"histamine": true,
		"other_amines": null,
		"liberator": false,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "vegetables"
	},
	{
		"id": 116,
		"name": "pumpkin",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "vegetables"
	},
	{
		"id": 117,
		"name": "radish",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "vegetables"
	},
	{
		"id": 118,
		"name": "red cabbage",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": null,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "vegetables"
	},
	{
		"id": 119,
		"name": "sauerkraut",
		"remarks": null,
		"histamine": true,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 3,
		"your_compatibility": null,
		"category": "vegetables"
	},
	{
		"id": 120,
		"name": "soy",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "vegetables"
	},
	{
		"id": 121,
		"name": "spinach",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "vegetables"
	},
	{
		"id": 122,
		"name": "squashes",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "vegetables"
	},
	{
		"id": 123,
		"name": "tomato",
		"remarks": null,
		"histamine": true,
		"other_amines": false,
		"liberator": true,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "vegetables"
	},
	{
		"id": 124,
		"name": "turnip",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": null,
		"your_compatibility": null,
		"category": "vegetables"
	},
	{
		"id": 125,
		"name": "zucchini",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "vegetables"
	},
	{
		"id": 126,
		"name": "basil",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "herbs"
	},
	{
		"id": 127,
		"name": "garlic",
		"remarks": "Small amounts are well tolerated",
		"histamine": false,
		"other_amines": false,
		"liberator": true,
		"blocker": false,
		"compatibility": 1,
		"your_compatibility": null,
		"category": "herbs"
	},
	{
		"id": 128,
		"name": "chives",
		"remarks": "Incompatible in large quantities",
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 1,
		"your_compatibility": null,
		"category": "herbs"
	},
	{
		"id": 129,
		"name": "dill",
		"remarks": "Small amounts usually not a problem. High salicylate content",
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 1,
		"your_compatibility": null,
		"category": "herbs"
	},
	{
		"id": 130,
		"name": "mint",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "herbs"
	},
	{
		"id": 131,
		"name": "oregano",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "herbs"
	},
	{
		"id": 132,
		"name": "pasrley",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "herbs"
	},
	{
		"id": 133,
		"name": "rosemary",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "herbs"
	},
	{
		"id": 134,
		"name": "sage",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "herbs"
	},
	{
		"id": 135,
		"name": "apple",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "fruits"
	},
	{
		"id": 136,
		"name": "apricot",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "fruits"
	},
	{
		"id": 137,
		"name": "avocado",
		"remarks": null,
		"histamine": true,
		"other_amines": false,
		"liberator": true,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "fruits"
	},
	{
		"id": 138,
		"name": "banana",
		"remarks": null,
		"histamine": false,
		"other_amines": true,
		"liberator": false,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "fruits"
	},
	{
		"id": 139,
		"name": "blackberry",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "fruits"
	},
	{
		"id": 140,
		"name": "blackcurrant",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "fruits"
	},
	{
		"id": 141,
		"name": "blueberry",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "fruits"
	},
	{
		"id": 142,
		"name": "starfruit",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "fruits"
	},
	{
		"id": 143,
		"name": "cherry",
		"remarks": "Controversial",
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "fruits"
	},
	{
		"id": 144,
		"name": "cocoa butter",
		"remarks": "Mostly well tolerated",
		"histamine": false,
		"other_amines": null,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "fruits"
	},
	{
		"id": 145,
		"name": "coconut",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "fruits"
	},
	{
		"id": 146,
		"name": "cocoa",
		"remarks": null,
		"histamine": false,
		"other_amines": true,
		"liberator": true,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "fruits"
	},
	{
		"id": 147,
		"name": "cranberry",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "fruits"
	},
	{
		"id": 148,
		"name": "dates",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "fruits"
	},
	{
		"id": 149,
		"name": "dragonfruit",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "fruits"
	},
	{
		"id": 150,
		"name": "figs",
		"remarks": "May be slightly laxative",
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 1,
		"your_compatibility": null,
		"category": "fruits"
	},
	{
		"id": 151,
		"name": "goji berry",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "fruits"
	},
	{
		"id": 152,
		"name": "grapefruit",
		"remarks": null,
		"histamine": false,
		"other_amines": true,
		"liberator": true,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "fruits"
	},
	{
		"id": 153,
		"name": "grapes",
		"remarks": null,
		"histamine": false,
		"other_amines": null,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "fruits"
	},
	{
		"id": 154,
		"name": "guava",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": null,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "fruits"
	},
	{
		"id": 155,
		"name": "kiwi druit",
		"remarks": null,
		"histamine": false,
		"other_amines": null,
		"liberator": true,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "fruits"
	},
	{
		"id": 156,
		"name": "lemon",
		"remarks": null,
		"histamine": false,
		"other_amines": null,
		"liberator": true,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "fruits"
	},
	{
		"id": 157,
		"name": "lime",
		"remarks": null,
		"histamine": false,
		"other_amines": null,
		"liberator": true,
		"blocker": false,
		"compatibility": 3,
		"your_compatibility": null,
		"category": "fruits"
	},
	{
		"id": 158,
		"name": "lingonberry",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "fruits"
	},
	{
		"id": 159,
		"name": "lychee",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "fruits"
	},
	{
		"id": 160,
		"name": "mandarin orange",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "fruits"
	},
	{
		"id": 161,
		"name": "mango",
		"remarks": "To be debated. Is often well tolerated.",
		"histamine": false,
		"other_amines": false,
		"liberator": null,
		"blocker": false,
		"compatibility": 1,
		"your_compatibility": null,
		"category": "fruits"
	},
	{
		"id": 162,
		"name": "melons (except watermelons)",
		"remarks": "Suspected occasional histamine liberator effects (due to pollutant / pesticide exposure)",
		"histamine": false,
		"other_amines": false,
		"liberator": null,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "fruits"
	},
	{
		"id": 163,
		"name": "orange",
		"remarks": null,
		"histamine": false,
		"other_amines": true,
		"liberator": true,
		"blocker": false,
		"compatibility": 3,
		"your_compatibility": null,
		"category": "fruits"
	},
	{
		"id": 164,
		"name": "papaya, paw paw",
		"remarks": null,
		"histamine": false,
		"other_amines": true,
		"liberator": true,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "fruits"
	},
	{
		"id": 165,
		"name": "peach",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "fruits"
	},
	{
		"id": 166,
		"name": "pear",
		"remarks": null,
		"histamine": false,
		"other_amines": true,
		"liberator": false,
		"blocker": false,
		"compatibility": 1,
		"your_compatibility": null,
		"category": "fruits"
	},
	{
		"id": 167,
		"name": "persimmon",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "fruits"
	},
	{
		"id": 168,
		"name": "passion fruit",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": null,
		"your_compatibility": null,
		"category": "fruits"
	},
	{
		"id": 169,
		"name": "pineapple",
		"remarks": null,
		"histamine": false,
		"other_amines": true,
		"liberator": true,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "fruits"
	},
	{
		"id": 170,
		"name": "plum",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": true,
		"blocker": false,
		"compatibility": 1,
		"your_compatibility": null,
		"category": "fruits"
	},
	{
		"id": 171,
		"name": "pomegranate",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "fruits"
	},
	{
		"id": 172,
		"name": "prune",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": true,
		"blocker": false,
		"compatibility": 1,
		"your_compatibility": null,
		"category": "fruits"
	},
	{
		"id": 173,
		"name": "raisins",
		"remarks": "Only if not sulphured / without sulphite / without preservatives! High salicylate content",
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "fruits"
	},
	{
		"id": 174,
		"name": "raspberry",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "fruits"
	},
	{
		"id": 175,
		"name": "rhubarb",
		"remarks": "Controversial. Often well tolerated. Oxalic acid",
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 1,
		"your_compatibility": null,
		"category": "fruits"
	},
	{
		"id": 176,
		"name": "rose hip",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": true,
		"blocker": false,
		"compatibility": 1,
		"your_compatibility": null,
		"category": "fruits"
	},
	{
		"id": 177,
		"name": "strawberry ",
		"remarks": null,
		"histamine": false,
		"other_amines": true,
		"liberator": true,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "fruits"
	},
	{
		"id": 178,
		"name": "watermelon",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": null,
		"blocker": false,
		"compatibility": 1,
		"your_compatibility": null,
		"category": "fruits"
	},
	{
		"id": 179,
		"name": "chia seed",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "seeds"
	},
	{
		"id": 180,
		"name": "psyllium seed husks",
		"remarks": "Can be useful both for constipation as well as diarrhea",
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "seeds"
	},
	{
		"id": 181,
		"name": "pumpkin seeds",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "seeds"
	},
	{
		"id": 182,
		"name": "sesame seeds",
		"remarks": "May cause diarrhea in some cases",
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 1,
		"your_compatibility": null,
		"category": "seeds"
	},
	{
		"id": 183,
		"name": "algae",
		"remarks": "Extremely rich in iodine",
		"histamine": false,
		"other_amines": false,
		"liberator": true,
		"blocker": false,
		"compatibility": 3,
		"your_compatibility": null,
		"category": "mushrooms, fungi and algae"
	},
	{
		"id": 184,
		"name": "kelp",
		"remarks": "Extremely rich in iodine",
		"histamine": false,
		"other_amines": false,
		"liberator": true,
		"blocker": false,
		"compatibility": 3,
		"your_compatibility": null,
		"category": "mushrooms, fungi and algae"
	},
	{
		"id": 185,
		"name": "kombu seaweed",
		"remarks": "Extremely rich in iodine",
		"histamine": false,
		"other_amines": false,
		"liberator": true,
		"blocker": false,
		"compatibility": 3,
		"your_compatibility": null,
		"category": "mushrooms, fungi and algae"
	},
	{
		"id": 186,
		"name": "mushrooms",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "mushrooms, fungi and algae"
	},
	{
		"id": 187,
		"name": "nori seaweed",
		"remarks": "Extremely rich in iodine",
		"histamine": false,
		"other_amines": false,
		"liberator": true,
		"blocker": false,
		"compatibility": 3,
		"your_compatibility": null,
		"category": "mushrooms, fungi and algae"
	},
	{
		"id": 188,
		"name": "porcino mushroom",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "mushrooms, fungi and algae"
	},
	{
		"id": 189,
		"name": "seaweed",
		"remarks": "Extremely rich in iodine",
		"histamine": false,
		"other_amines": false,
		"liberator": true,
		"blocker": false,
		"compatibility": 3,
		"your_compatibility": null,
		"category": "mushrooms, fungi and algae"
	},
	{
		"id": 190,
		"name": "wakame seaweed",
		"remarks": "Extremely rich in iodine",
		"histamine": false,
		"other_amines": false,
		"liberator": true,
		"blocker": false,
		"compatibility": 3,
		"your_compatibility": null,
		"category": "mushrooms, fungi and algae"
	},
	{
		"id": 191,
		"name": "white button mushroom",
		"remarks": null,
		"histamine": false,
		"other_amines": true,
		"liberator": false,
		"blocker": false,
		"compatibility": 1,
		"your_compatibility": null,
		"category": "mushrooms, fungi and algae"
	},
	{
		"id": 192,
		"name": "yeast",
		"remarks": "Well tolerated when produced under perfect hygienic conditions. Exceptions: baked goods with a long dough fermentation time may be intolerated. High content of glutamic acid",
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 1,
		"your_compatibility": null,
		"category": "mushrooms, fungi and algae"
	},
	{
		"id": 193,
		"name": "agave nectar, agave syrup",
		"remarks": "High fructose content",
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "sweeteners"
	},
	{
		"id": 194,
		"name": "artificial sweeteners",
		"remarks": "Sucralose is tolerated",
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 1,
		"your_compatibility": null,
		"category": "sweeteners"
	},
	{
		"id": 195,
		"name": "xylitol",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "sweeteners"
	},
	{
		"id": 196,
		"name": "caramel",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "sweeteners"
	},
	{
		"id": 197,
		"name": "sorbitol",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "sweeteners"
	},
	{
		"id": 198,
		"name": "dextrose",
		"remarks": "Glucose syrup may contain a lot of fructose, pure glucose is free from fructose",
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "sweeteners"
	},
	{
		"id": 199,
		"name": "extract of malt",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "sweeteners"
	},
	{
		"id": 200,
		"name": "fructose",
		"remarks": "Excessive amounts will cause indigestion",
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "sweeteners"
	},
	{
		"id": 201,
		"name": "glucose",
		"remarks": "Glucose syrup may contain a lot of fructose, pure glucose is free from fructose",
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "sweeteners"
	},
	{
		"id": 202,
		"name": "honey",
		"remarks": "To be debated. Naturally contains benzoic acid",
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "sweeteners"
	},
	{
		"id": 203,
		"name": "lactose",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "sweeteners"
	},
	{
		"id": 204,
		"name": "malt extract",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "sweeteners"
	},
	{
		"id": 205,
		"name": "maltose",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "sweeteners"
	},
	{
		"id": 206,
		"name": "maple syrup",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "sweeteners"
	},
	{
		"id": 207,
		"name": "palm sugar",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": null,
		"blocker": false,
		"compatibility": null,
		"your_compatibility": null,
		"category": "sweeteners"
	},
	{
		"id": 208,
		"name": "stevia",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "sweeteners"
	},
	{
		"id": 209,
		"name": "sucrose",
		"remarks": "Nevertheless, should be used sparingly, not as a main nutrient",
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "sweeteners"
	},
	{
		"id": 210,
		"name": "sugar",
		"remarks": "Nevertheless, should be used sparingly, not as a main nutrient",
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "sweeteners"
	},
	{
		"id": 211,
		"name": "anise, anise seed",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": null,
		"your_compatibility": null,
		"category": "spices, seasoning, aroma"
	},
	{
		"id": 212,
		"name": "bay laurel",
		"remarks": "Small amounts are well tolerated, for larger quantities lack of experience",
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": null,
		"your_compatibility": null,
		"category": "spices, seasoning, aroma"
	},
	{
		"id": 213,
		"name": "black seed",
		"remarks": "Antiallergic",
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "spices, seasoning, aroma"
	},
	{
		"id": 214,
		"name": "bouillon",
		"remarks": "Almost always with incompatible ingredients (glutamate, yeast extract, spice/aroma/flavour/seasoning/condiment/wort (in the meaning of protein hydrolysates), meat extracts, incompatible vegetables)",
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "spices, seasoning, aroma"
	},
	{
		"id": 215,
		"name": "cardamom",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "spices, seasoning, aroma"
	},
	{
		"id": 216,
		"name": "cilantro, coriander",
		"remarks": "Only small amounts are well tolerated",
		"histamine": false,
		"other_amines": false,
		"liberator": null,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "spices, seasoning, aroma"
	},
	{
		"id": 217,
		"name": "cinnamon",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "spices, seasoning, aroma"
	},
	{
		"id": 218,
		"name": "cloves",
		"remarks": "Small amounts are well tolerated, for larger quantities lack of experience",
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "spices, seasoning, aroma"
	},
	{
		"id": 219,
		"name": "cumin",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": true,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "spices, seasoning, aroma"
	},
	{
		"id": 220,
		"name": "curry",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "spices, seasoning, aroma"
	},
	{
		"id": 221,
		"name": "vinegar, spirit vinegar, distilled white vinegar",
		"remarks": "Low histamine, but not free from histamine. Use sparingly. Check for intolerated additives",
		"histamine": null,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "spices, seasoning, aroma"
	},
	{
		"id": 222,
		"name": "ginger",
		"remarks": "Small amounts are well tolerated",
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 1,
		"your_compatibility": null,
		"category": "spices, seasoning, aroma"
	},
	{
		"id": 223,
		"name": "fennel flower",
		"remarks": "Antiallergic",
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "spices, seasoning, aroma"
	},
	{
		"id": 224,
		"name": "meat extract",
		"remarks": null,
		"histamine": null,
		"other_amines": null,
		"liberator": null,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "spices, seasoning, aroma"
	},
	{
		"id": 225,
		"name": "mustard, mustard seed, mustard seed powder",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": true,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "spices, seasoning, aroma"
	},
	{
		"id": 226,
		"name": "nutmeg",
		"remarks": "Small amounts are well tolerated",
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 1,
		"your_compatibility": null,
		"category": "spices, seasoning, aroma"
	},
	{
		"id": 227,
		"name": "paprika, hot",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "spices, seasoning, aroma"
	},
	{
		"id": 228,
		"name": "paprika, sweet",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "spices, seasoning, aroma"
	},
	{
		"id": 229,
		"name": "pepper, black",
		"remarks": "Small amounts are well tolerated",
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "spices, seasoning, aroma"
	},
	{
		"id": 230,
		"name": "pepper, white",
		"remarks": "Small amounts are well tolerated",
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "spices, seasoning, aroma"
	},
	{
		"id": 231,
		"name": "persian cumin",
		"remarks": "Positive effect: good for heavy meals. Caution: Not to be confused with cumin",
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "spices, seasoning, aroma"
	},
	{
		"id": 232,
		"name": "poppy seeds",
		"remarks": "Small amounts are well tolerated",
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 1,
		"your_compatibility": null,
		"category": "spices, seasoning, aroma"
	},
	{
		"id": 233,
		"name": "red wine vinegar",
		"remarks": null,
		"histamine": true,
		"other_amines": null,
		"liberator": false,
		"blocker": false,
		"compatibility": 3,
		"your_compatibility": null,
		"category": "spices, seasoning, aroma"
	},
	{
		"id": 234,
		"name": "seasoning made of hydrolysated proteins",
		"remarks": "Derived from vegetal protein hydrolysate, aroma reminiscent of meat broth. Contains glutamate, histamine and other amines",
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "spices, seasoning, aroma"
	},
	{
		"id": 235,
		"name": "soy sauce",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 3,
		"your_compatibility": null,
		"category": "spices, seasoning, aroma"
	},
	{
		"id": 236,
		"name": "thyme",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "spices, seasoning, aroma"
	},
	{
		"id": 237,
		"name": "turmeric",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "spices, seasoning, aroma"
	},
	{
		"id": 238,
		"name": "vanilla extract",
		"remarks": null,
		"histamine": null,
		"other_amines": false,
		"liberator": null,
		"blocker": false,
		"compatibility": 1,
		"your_compatibility": null,
		"category": "spices, seasoning, aroma"
	},
	{
		"id": 239,
		"name": "vanilla",
		"remarks": null,
		"histamine": null,
		"other_amines": false,
		"liberator": null,
		"blocker": false,
		"compatibility": 1,
		"your_compatibility": null,
		"category": "spices, seasoning, aroma"
	},
	{
		"id": 240,
		"name": "apple cider vinegar",
		"remarks": "Check for additives",
		"histamine": true,
		"other_amines": null,
		"liberator": false,
		"blocker": false,
		"compatibility": 1,
		"your_compatibility": null,
		"category": "spices, seasoning, aroma"
	},
	{
		"id": 241,
		"name": "white wine vinegar",
		"remarks": null,
		"histamine": true,
		"other_amines": null,
		"liberator": false,
		"blocker": false,
		"compatibility": 3,
		"your_compatibility": null,
		"category": "spices, seasoning, aroma"
	},
	{
		"id": 242,
		"name": "yeast extract",
		"remarks": "Chemical conversion to glutamate",
		"histamine": false,
		"other_amines": false,
		"liberator": true,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "spices, seasoning, aroma"
	},
	{
		"id": 243,
		"name": "spring water",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": null,
		"blocker": false,
		"compatibility": 1,
		"your_compatibility": null,
		"category": "water"
	},
	{
		"id": 244,
		"name": "mineral water",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "water"
	},
	{
		"id": 245,
		"name": "tap water",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "water"
	},
	{
		"id": 246,
		"name": "beer",
		"remarks": null,
		"histamine": true,
		"other_amines": true,
		"liberator": true,
		"blocker": true,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "alcoholic beverages"
	},
	{
		"id": 247,
		"name": "brandy",
		"remarks": null,
		"histamine": true,
		"other_amines": true,
		"liberator": true,
		"blocker": true,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "alcoholic beverages"
	},
	{
		"id": 248,
		"name": "champagne",
		"remarks": null,
		"histamine": true,
		"other_amines": true,
		"liberator": true,
		"blocker": true,
		"compatibility": 3,
		"your_compatibility": null,
		"category": "alcoholic beverages"
	},
	{
		"id": 249,
		"name": "rum",
		"remarks": null,
		"histamine": true,
		"other_amines": true,
		"liberator": true,
		"blocker": true,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "alcoholic beverages"
	},
	{
		"id": 250,
		"name": "sparkling wine",
		"remarks": null,
		"histamine": true,
		"other_amines": true,
		"liberator": true,
		"blocker": true,
		"compatibility": 3,
		"your_compatibility": null,
		"category": "alcoholic beverages"
	},
	{
		"id": 251,
		"name": "spirits (not colourless)",
		"remarks": null,
		"histamine": true,
		"other_amines": true,
		"liberator": true,
		"blocker": true,
		"compatibility": 3,
		"your_compatibility": null,
		"category": "alcoholic beverages"
	},
	{
		"id": 252,
		"name": "spirits (colourless)",
		"remarks": null,
		"histamine": null,
		"other_amines": null,
		"liberator": true,
		"blocker": true,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "alcoholic beverages"
	},
	{
		"id": 253,
		"name": "wine",
		"remarks": null,
		"histamine": true,
		"other_amines": true,
		"liberator": true,
		"blocker": true,
		"compatibility": 3,
		"your_compatibility": null,
		"category": "alcoholic beverages"
	},
	{
		"id": 254,
		"name": "red wine",
		"remarks": null,
		"histamine": true,
		"other_amines": true,
		"liberator": true,
		"blocker": true,
		"compatibility": 3,
		"your_compatibility": null,
		"category": "alcoholic beverages"
	},
	{
		"id": 255,
		"name": "white wine",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "alcoholic beverages"
	},
	{
		"id": 256,
		"name": "chamomile tea",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "tea and herbal infusions"
	},
	{
		"id": 257,
		"name": "green tea",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": true,
		"compatibility": 1,
		"your_compatibility": null,
		"category": "tea and herbal infusions"
	},
	{
		"id": 258,
		"name": "herbal tea",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": null,
		"blocker": false,
		"compatibility": 1,
		"your_compatibility": null,
		"category": "tea and herbal infusions"
	},
	{
		"id": 259,
		"name": "lime blossom tea",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "tea and herbal infusions"
	},
	{
		"id": 260,
		"name": "peppermint ea",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "tea and herbal infusions"
	},
	{
		"id": 261,
		"name": "rooibos tea",
		"remarks": "Caution: Check the list of ingredients. Tea blends (mixtures) of Rooibos & incompatible ingredients (e.g. orange zest) are often sold as “Rooibos” as well",
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "tea and herbal infusions"
	},
	{
		"id": 262,
		"name": "sage tea",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "tea and herbal infusions"
	},
	{
		"id": 263,
		"name": "black tea",
		"remarks": null,
		"histamine": true,
		"other_amines": false,
		"liberator": false,
		"blocker": true,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "tea and herbal infusions"
	},
	{
		"id": 264,
		"name": "verbena herbal tea",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "tea and herbal infusions"
	},
	{
		"id": 265,
		"name": "orange juice",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": true,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "juices"
	},
	{
		"id": 266,
		"name": "tomato juice",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": true,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "juices"
	},
	{
		"id": 267,
		"name": "coca-cola",
		"remarks": "See also caffeine and carbonated",
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 1,
		"your_compatibility": null,
		"category": "caffeinated drinks"
	},
	{
		"id": 268,
		"name": "coffee",
		"remarks": "Caffeine stimulates nerves and bowel, which may be mast cell activating",
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 1,
		"your_compatibility": null,
		"category": "caffeinated drinks"
	},
	{
		"id": 269,
		"name": "energy drinks",
		"remarks": "Theobromine inhibits the DAO enzyme",
		"histamine": false,
		"other_amines": false,
		"liberator": null,
		"blocker": true,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "caffeinated drinks"
	},
	{
		"id": 270,
		"name": "oat drink, oat milk ",
		"remarks": "Often slightly histamine containing as fermented enzymatically",
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 1,
		"your_compatibility": null,
		"category": "milk substitutes"
	},
	{
		"id": 271,
		"name": "rice drink, rice milk ",
		"remarks": "Often slightly histamine containing as fermented enzymatically",
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 1,
		"your_compatibility": null,
		"category": "milk substitutes"
	},
	{
		"id": 272,
		"name": "soy drink, soy milk",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "milk substitutes"
	},
	{
		"id": 273,
		"name": "chocolate drinks",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "soft drinks"
	},
	{
		"id": 274,
		"name": "cocoa drinks",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "soft drinks"
	},
	{
		"id": 275,
		"name": "elderflower cordial",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "soft drinks"
	},
	{
		"id": 276,
		"name": "lemonade",
		"remarks": "Depending on the ingredients",
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 1,
		"your_compatibility": null,
		"category": "soft drinks"
	},
	{
		"id": 277,
		"name": "Ovaltine",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "soft drinks"
	},
	{
		"id": 278,
		"name": "soda",
		"remarks": "Depending on the ingredients",
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 1,
		"your_compatibility": null,
		"category": "soft drinks"
	},
	{
		"id": 279,
		"name": "soft drinks",
		"remarks": "Depending on the ingredients",
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 1,
		"your_compatibility": null,
		"category": "soft drinks"
	},
	{
		"id": 280,
		"name": "lard",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 0,
		"your_compatibility": null,
		"category": "miscellaneous"
	},
	{
		"id": 281,
		"name": "chocolate",
		"remarks": null,
		"histamine": false,
		"other_amines": true,
		"liberator": false,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "miscellaneous"
	},
	{
		"id": 282,
		"name": "white chocolate",
		"remarks": "Mostly well tolerated",
		"histamine": false,
		"other_amines": null,
		"liberator": false,
		"blocker": false,
		"compatibility": 1,
		"your_compatibility": null,
		"category": "miscellaneous"
	},
	{
		"id": 283,
		"name": "mustard",
		"remarks": null,
		"histamine": true,
		"other_amines": false,
		"liberator": true,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "miscellaneous"
	},
	{
		"id": 284,
		"name": "tofu",
		"remarks": null,
		"histamine": false,
		"other_amines": false,
		"liberator": false,
		"blocker": false,
		"compatibility": 2,
		"your_compatibility": null,
		"category": "miscellaneous"
	}
]

const performSeed = async () => {
	const createdIngredients = await Ingredient.insertMany(ingredients);
	console.log(`Created ${createdIngredients.length} ingredients`);
}

performSeed();

setInterval(()=>{
	console.log("Countdown 2s and exit...");
    process.exit(0);
}, 2000)